---
- name: install php on apache (redhat machine)
  become: yes
  hosts: all
  tasks:
    - name: install apache and php
      ansible.builtin.dnf:
        name: 
          - httpd  
          - php
          - php-cli 
          - php-common 
          - php-gd 
          - php-mysqlnd php-pdo 
        state: present
    - name: create a file
      ansibe.builtin.copy:
        content: <?php phpinfo(); ?>
        dest: /etc/www/html/info.php
    - name: start service
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started