---
- name: install php on apache (ubuntu and red hat) only one playbook
  become: yes
  hosts: webservers
  tasks:
    - name: checking os 
      ansible.builtin.fail:
        msg: this is unsupported os - "it support ubuntu and redhat"
      when: ansible_facts["_os_family"] != "Debian" and ansible_facts["_os_family"] != "RedHat"
    
    - name: print all variables
      ansible.builtin.debug:
        var: all_packages

    - name: install php and apache 
      ansible.builtin.apt:
        name: {{ all_packages }} 
        state: present
        update_cache: yes
      when: ansible_facts["os_family"] == "Debian" 

    - name: install httpd and php 
      ansible.builtin.dnf:
        name: {{ all_packages }} 
        state: present
      when: ansible_facts["os_family"] == "RedHat" 

    - name: create a file info.php  
      ansible.builtin.copy:
        conten: <?php phpinfo(); ?>
        dest: /var/www/html/info.php
        
    - name: start the service 
      ansible.builtin.service:
        name: {{ package_name }}
        enabled: yes
        state: started
      when: ansible_facts["os_family"] == "RedHat" 
